### ISSUE TITLE
pasting in url with `/issues` does not work

### ISSUE THREAD

**Issue by esaruoho** [tobycm/get-back-to-work#1]
if i paste in a url with `/issues` at the end
i get no results

**Comment by esaruoho** [comment]
ok i'm working on a PR
<img width="897" alt="Screenshot 2024-10-08 at 13 00 24" src="https://github.com/user-attachments/assets/33990000-c4e9-409a-91f7-fffe7b1c66e3">

**Comment by tobycm** [comment]
Thanks, I will take a look and merge it later.
